#!/usr/bin/env bash
# Prints "To infinity and beyond" indefinitely
# Prints "I am invincible!!!" with each iteration
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
