#!/usr/bin/env bash
# Print numbers from 1 to 20 in and:
#   "bad luck from China" in 4th iteration
#   "bad luck from Japan" in 9th iteration
#   "bad luck from Italy" in 17th iteration
count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
